runelite.title=RuneLite
runelite.version=${project.version}
runelite.commit=${git.commit.id.abbrev}
runelite.dirty=${git.dirty}
runelite.discord.enable=false
runelite.discord.appid=409416265891971072
runelite.discord.invite=https://discord.gg/ArdAhnN
runelite.github.link=https://github.com/runelite/runelite/discussions
runelite.wiki.link=https://github.com/runelite/runelite/wiki
runelite.patreon.link=https://www.patreon.com/runelite
runelite.wiki.troubleshooting.link=https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client
runelite.wiki.building.link=https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA#client-failing-to-start
runelite.dnschange.link=https://1.1.1.1/dns/#setup-instructions
runelite.jav_config=http://127.0.0.1:43600/javconfig.ws
runelite.jav_config_backup=http://127.0.0.1:43600/javconfig.ws
runelite.pluginhub.url=http://127.0.0.1:43600/plugins
runelite.pluginhub.version=${project.version}
runelite.api.base=http://127.0.0.1:43600/rl-api
runelite.session=http://127.0.0.1:43600/session
runelite.static.base=http://127.0.0.1:43600
runelite.ws=http://127.0.0.1:43600/ws
runelite.config=http://127.0.0.1:43600/config.json
runelite.osrstwitter.link=about:blank
runelite.oauth.redirect=http://127.0.0.1:43600/logged-in
runelite.jagex.domainblock=.discord.com,.runescape.wiki
